name: Deploy Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  serve_production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Rust toolchain
        run: rustup target add wasm32-unknown-unknown

      - name: Download Trunk executable
        run: |
          wget -qO trunk.tar.gz https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf trunk.tar.gz
          sudo chmod a+x trunk
          sudo mv trunk /bin/trunk
      
      - name: Download tailwindcss executable
        run: |
          wget -qO tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.8/tailwindcss-linux-x64
          sudo chmod a+x tailwindcss
          sudo mv tailwindcss /bin/tailwindcss

      - name: Build with Trunk
        run: trunk build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
